# This is a basic workflow to help you get started with Actions

name: Creates a PR for cko-gateway changes in documentation around cko-gateway

on:
  push:
    branches:      
      - 'master'  

env:
  CI: true
  PAT: ${{ secrets.PAT }}

jobs:
  upload-spec:
    runs-on: ubuntu-latest
    steps: 
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - uses: actions/checkout@v2
        with:
          persist-credentials: true
          repository: cko-gateway/checkout-api-reference
          ref: ${{ steps.extract_branch.outputs.branch }}

      - name: Delete non-Demo files
        run: |
          echo ********** Listing contents of abc_spec/ ************
          ls abc_spec/*/**
          echo ********** Created an empty folder ************
          mkdir newspec
          mkdir -p newspec/abc_spec
          echo ********** Copying over what we need into the new folder ************
          mkdir -p newspec/abc_spec/components/schemas
          cp -r abc_spec/components/schemas/* newspec/abc_spec/components/schemas
          mkdir -p newspec/abc_spec/paths
          cp -r abc_spec/paths/* newspec/abc_spec/paths
          echo ********** Listing contents of newspec/ ************
          ls newspec/abc_spec/*/**
          echo ********** Creating copies of spec for ABC ************
          cp -r newspec/abc_spec/ abc_spec/

          echo ********** Listing contents of nas_spec/ ************
          ls nas_spec/*/**
          echo ********** Created an empty folder ************
          mkdir -p newspec/nas_spec
          echo ********** Copying over what we need into the new folder ************
          mkdir -p newspec/nas_spec/components/schemas
          cp -r nas_spec/components/schemas/* newspec/nas_spec/components/schemas
          mkdir -p newspec/nas_spec/paths
          cp -r nas_spec/paths/* newspec/nas_spec/paths
          echo ********** Listing contents of newspec/ ************
          ls newspec/nas_spec/*/**
          echo ********** Creating copies of spec for NAS ************
          cp -r newspec/nas_spec/ nas_spec/

          echo ********** Ready to upload specs ************

      - uses: actions/upload-artifact@v2
        with:
          name: specification
          path: newspec/

  publish-spec:
    runs-on: ubuntu-latest
    needs: upload-spec
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: specification
          path: src_spec

      - name: Fetch Checkout Api Reference repository
        uses: actions/checkout@v2
        with:
          repository: checkout/checkout-api-reference
          ref: master
          token: ${{ env.PAT }}
          path: src

      - name: Commit Api specification
        working-directory: src
        run: |
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com" && git config user.name "$GITHUB_ACTOR"
          git branch -m "cko-gateway/Api-Spec"
          rsync -a ../src_spec/abc_spec/ abc_spec/
          rsync -a ../src_spec/nas_spec/ nas_spec/
          git add .
          git commit -m 'Publish new API Specification'
          git push -f origin HEAD

      - uses: actions/github-script@v4
        with:
          github-token: ${{ env.PAT }}
          script: |
            await github.pulls.create({
              owner: 'checkout',
              repo: 'checkout-api-reference',
              head: "cko-gateway/Api-Spec",
              base: 'master',
              title: "cko-gateway: Update API Specification"
            });
